vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        partitions_images:
            uri_prefix: /images/partitions
            upload_destination: '%kernel.project_dir%/public/images/partitions'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
